language: node_js

node_js:
  - "8.11.1"

services:
  - mysql

before_install:
  - mysql -u root -e 'create database test_frappejs'
  - echo "USE mysql;\nCREATE USER 'test_frappejs'@'localhost' IDENTIFIED BY 'test_frappejs';\nFLUSH PRIVILEGES;\n"
  - echo "USE mysql;\nGRANT ALL PRIVILEGES ON \`test_frappejs\`.* TO 'test_frappejs'@'localhost';\n"
  - "npm install -g yarn"
  - "yarn"

script:
  - "yarn link && yarn link frappejs"
  - "yarn run test"
